In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [5]:
import numpy as np

my_array = np.array([[11, 12, 13, 14],
                    [15, 16, 17, 18]])

print(my_array)

[[11 12 13 14]
 [15 16 17 18]]


In [6]:
import numpy as np

my_array = np.zeros((4, 3))

print(my_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
my_array = np.ones((3, 4))

print(my_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
my_array = np.arange(4, 14)

print(my_array)

[ 4  5  6  7  8  9 10 11 12 13]


In [9]:
my_array = np.array([0.0, 1.5, 3.0, 4.5])

print(my_array)

[0.  1.5 3.  4.5]


In [10]:
my_array = np.full((2, 2), 4)

print(my_array)

[[4 4]
 [4 4]]


In [11]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
diagonal_elements = [10, 12]

diagonal_matrix = np.diag(diagonal_elements)

print(diagonal_matrix)

[[10  0]
 [ 0 12]]


In [13]:
np.random.seed(0)

random_array = np.random.uniform(0, 10, (3, 3))

print(random_array)

[[5.48813504 7.15189366 6.02763376]
 [5.44883183 4.23654799 6.45894113]
 [4.37587211 8.91773001 9.63662761]]


In [14]:
np.random.seed(0)

random_array = np.random.randint(10, 21, size=(3, 3))

print(random_array)

[[15 10 13]
 [13 17 19]
 [13 15 12]]


In [15]:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

sub_array = myArray[0, :2]

print(sub_array)

[11 12]


In [16]:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

myArray[:2, :] = 0

print(myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]


In [17]:
my_array = np.arange(21)

reversed_array = my_array[::-1]

print(reversed_array)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [18]:
myArray = np.array([[11, 12, 13], [14, 15, 16]])

reshaped_array = myArray.reshape(3, -1)

print(reshaped_array)

[[11 12]
 [13 14]
 [15 16]]


In [19]:
myArray = np.arange(10)

squared_array = np.square(myArray)

square_root_array = np.sqrt(myArray)

result_array = squared_array * square_root_array

print(myArray)

print(squared_array)

print(square_root_array)

print(result_array)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[  0.           1.           5.65685425  15.58845727  32.
  55.90169944  88.18163074 129.64181424 181.01933598 243.        ]


In [22]:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

new_row = np.array([20, 21, 22])
myArray = np.vstack((myArray, new_row))

new_column = np.array([30, 40, 50])
myArray = np.column_stack((myArray, new_column))

print(myArray)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [23]:
import numpy as np

myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

new_row = np.array([20, 21, 22])
myArray = np.vstack((myArray, new_row))

new_column = np.array([30, 40, 50])
myArray = np.column_stack((myArray, new_column))

print(myArray)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 3

In [1]:
import numpy as np

myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

myArray = np.vstack([myArray, [20, 21, 22]])

myArray = np.hstack([myArray, np.array([[30], [40], [50], [60]])])

In [2]:
import numpy as np

myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

myArray = np.vstack([myArray, [20, 21, 22]])

myArray = np.hstack([myArray, np.array([[30], [40], [50], [60]])])

print(myArray)

[[11 12 13 30]
 [14 15 16 40]
 [17 18 19 50]
 [20 21 22 60]]


In [3]:
myArray = np.zeros((2,2))
myArray = np.insert(myArray, 1, 1, axis=1)

myArray = np.insert(myArray, 2, 2, axis=0)

myArray = np.delete(myArray, -1, axis=1)

myArray = np.delete(myArray, -1, axis=0)

print(myArray)

[[0. 1.]
 [0. 1.]]


In [4]:
myArray = np.matrix([[1, 2, 3], [4, 5, 6], [9, 8, 7]])

myArray = np.delete(myArray, 1, axis=1)

print(myArray)

[[1 3]
 [4 6]
 [9 7]]


In [5]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
exercise_1[exercise_1 % 2 != 0] = -1

print(exercise_1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [6]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]).reshape(3, -1)

print(exercise_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
exercise_3 = np.arange(4).reshape(2, -1) + 202

print(exercise_3)

[[202 203]
 [204 205]]


In [9]:
exercise_4 = np.random.randint(30, 41, size=10)

print(exercise_4)

[33 40 39 35 32 40 37 39 38 35]


In [10]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])
positions_gt = np.where(x > y)
positions_eq = np.where(x == y)

print(positions_gt)
print(positions_eq)

(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),)
(array([0], dtype=int64),)


In [11]:
exercise_6 = np.arange(100).reshape(5, -1)[:, :4]

print(exercise_6)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]
