In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)  # seed for reproducibility

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [5]:
import numpy as np

my_array = np.array([[11, 12, 13, 14],
                    [15, 16, 17, 18]])

print(my_array)

[[11 12 13 14]
 [15 16 17 18]]


In [6]:
import numpy as np

my_array = np.zeros((4, 3))

print(my_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
my_array = np.ones((3, 4))

print(my_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
my_array = np.arange(4, 14)

print(my_array)

[ 4  5  6  7  8  9 10 11 12 13]


In [9]:
my_array = np.array([0.0, 1.5, 3.0, 4.5])

print(my_array)

[0.  1.5 3.  4.5]


In [10]:
my_array = np.full((2, 2), 4)

print(my_array)

[[4 4]
 [4 4]]


In [11]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
diagonal_elements = [10, 12]

diagonal_matrix = np.diag(diagonal_elements)

print(diagonal_matrix)

[[10  0]
 [ 0 12]]


In [13]:
np.random.seed(0)

random_array = np.random.uniform(0, 10, (3, 3))

print(random_array)

[[5.48813504 7.15189366 6.02763376]
 [5.44883183 4.23654799 6.45894113]
 [4.37587211 8.91773001 9.63662761]]


In [14]:
np.random.seed(0)

random_array = np.random.randint(10, 21, size=(3, 3))

print(random_array)

[[15 10 13]
 [13 17 19]
 [13 15 12]]


In [15]:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

sub_array = myArray[0, :2]

print(sub_array)

[11 12]


In [16]:
myArray = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])

myArray[:2, :] = 0

print(myArray)

[[ 0  0  0]
 [ 0  0  0]
 [17 18 19]]
